### ISSUE TITLE
integrate argcomplete with PRG

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#120]
- [ ] add requirement to spec file
- [ ] attach it to argparser ref: https://argcomplete.readthedocs.org/en/latest/

**Comment by jsilhan** [comment]
taken from @auchytil . @LukasSlouka or @PavolVican implement it by one of you or do it together.

**Comment by cibo94** [comment]
This is done, right? should be closed

**Comment by PavolVican** [comment]
Yes, it is done.
