### ISSUE TITLE
Do doc setup

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#121]
- [ ] see how the documentation files are managed in DNF https://github.com/rpm-software-management/dnf/tree/master/doc
- [ ] set the CMakefile to generate hmtl and man pages
- [ ] include man pages in spec
- [ ] add Sphinx requirement in spec

**Comment by LukasSlouka** [comment]
Should I prepare command_ref.rst and conf_ref.rst files for manual pages 8 and 5 (by prepare I mean create empty files)? I suppose they would surely be completed later and It would allow me to make broader setup without causing errors.

**Comment by jsilhan** [comment]
`conf_ref.rst` is not needed in RPG. You can even document all command options from `rpg/conf.py` to `command_ref.rst`

**Comment by jsilhan** [comment]
in another issue https://github.com/rh-lab-q/rpg/issues/198 and commit into this pull request. The code looks good so far.
