### ISSUE TITLE
move pages from wiki to doc inside project dir

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#123]
migrate this https://github.com/rh-lab-q/rpg/wiki/Writing-plugins
depends on #121

**Comment by jsilhan** [comment]
Move just [writing plugins](https://github.com/rh-lab-q/rpg/wiki/Writing-plugins) from wiki page. Note that some of the method are outdated. Check them (/rpg/rpg/plugin) and mention with links appropriate Base calls i.e.: run_raw_sources_analysis, run_raw_compiled_analysis, etc.

**Comment by LukasSlouka** [comment]
I believe you meant that phases are outdated, rather than methods
