### ISSUE TITLE
show files when str(spec) called

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#124]
- [ ] remove `write` and `_write*` methods
- [ ] write tests to prove files are in result string
- [ ] implement `Subpackage._get_files()`
- [ ] append `_get_files()` to result in `__str__()`

**Comment by Shootervm** [comment]
* should I get rid of all `write` and `_write*` methods in Spec ? or just ones in Subpacage class ?
* will `_get_files()` be only a simple getter that will return an files array ? or is there something more to implement ?

**Comment by jsilhan** [comment]
> should I get rid of all `write` and `_write*` methods in Spec ? or just ones in Subpacage class ?

all of them, `__str__` already converts attributes to string used in rpm spec.

> will `_get_files()` be only a simple getter that will return an files array ? or is there something more to implement ?

It should return a string as other `_get_*` methods

**Comment by Shootervm** [comment]
_get_files() = `%files\n` + str(f1) + str(f2) ...

**Comment by jsilhan** [comment]
@cibo94 ask Vojta about his progress and assign it to you / help him, please.

**Comment by cibo94** [comment]
This should be done with 3941cd2
