### ISSUE TITLE
implement files_to_pkgs plugin

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#128]
It should use dnf sack and convert all (Build)Requires files to packages.
in phase `installed` it should transfer all `File` objects from spec.Requires and spec.Builrequires to packages using hawkey.Selector(file=<file>) passed into hawkey.Goal.install(<selector>)

**Comment by cibo94** [comment]
This is really hard, because for instance in our project there are a lot of files to be resolved which takes loads of time (~5 minutes). So is there any optimization, something like hakwey will not search whole repo for only one file?
...

I have tried to do something like this:
```python
_goal = hawkey.Goal(self.sack)
_query = hawkey.Query(self.sack)
for _file in self.spec.Requires:
    map(_goal.install, _query.filter(file=_file))
_goal.run()
```
But there is nothing about this in documentation of hawkey or dnf.

**Comment by cibo94** [comment]
```python
_goal = hawkey.Goal(self.sack)
for _file in self.spec.Requires:
    sltr = hawkey.Selector(self.sack).set(file=_file)
    _goal.install(select=sltr)
_goal.run()
print(_goal.list_installs())
```
This is failing on _goal.install and when i have tried this:
```python
for _file in self.spec.Requires:
    _goal = hawkey.Goal(self.sack)
    sltr = hawkey.Selector(self.sack).set(file=_file)
    _goal.install(select=sltr)
    _goal.run()
    print(_goal.list_installs())
```
It prints empty lists and fails after few loops (~40 seconds).

I have working solution, but it takes 80 seconds to resolve hawkey require dependencies. It looks like this:
```python
def _resolve(files, query):
    for _file in files:
        yield [str(pckg) for pckg in query.filter(file=_file)]

def _uniq(_list):
    return list(set(_list))

import itertools
_query = hawkey.Query(self.sack)
self.spec.Requires = _uniq(
    itertools.chain(*list(_resolve(self.spec.Requires, _query))))
self.spec.BuildRequires = _uniq(
    itertools.chain(*list(_resolve(self.spec.BuildRequires, _query))))
```
