### ISSUE TITLE
implement maven plugin

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#130]

**Comment by LukasSlouka** [comment]
I started doing this and I noticed I can extract some project information like `name`, `version`, `url` and `description` from `pom.xml` file right after extraction. However our GUI does not support suggesting these values, although many of them might be evident just from tarball name. I think @regeciovad could code this behavior like she did in other pages:

```python
    def initializePage(self):
        self.nameEdit.setText(self.base.spec.Name)
        self.versionEdit.setText(self.base.spec.Version)
        ...
```

**Comment by regeciovad** [comment]
I can do this, but url in second page and url in copr are two different things.
But yes, suggestion of name and other information would be nice.

**Comment by LukasSlouka** [comment]
nope, I mean in what you called `mandatory page` in your wizard, so basicaly `spec.Name`. I don't know how it is connected to copr

**Comment by regeciovad** [comment]
But in mandatory page we don't know name and others information.
In copr page user fills up these information again.
Where else you want to suggest these info?

**Comment by LukasSlouka** [comment]
Ah okay, nevermind then. I just thought we may suggest something there even though we don't know these information

**Comment by jsilhan** [comment]
@LukasSlouka good idea, created new issue https://github.com/rh-lab-q/rpg/issues/280
