### ISSUE TITLE
'spec.Source' should be name of tarball

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#155]
Building is failing because spec.Source is path to source not a name of tarball with source.

For instance, when building RPG from source directory, in spec file line with Source variable is:
```
Source: /home/onionka/Projects/rpg
```

This should be set to ```${project_name}-${version}.tar.gz``` or something like that.

**Comment by jsilhan** [comment]
true. The `spec.Source = ${project_name}-${version}.tar.gz` should be set once version is known (in `Base.create_archive`.
