### ISSUE TITLE
make travis CI mock build rpm when commit is pushed

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#159]
it should upload the result rpm somewhere to accessible storage

**Comment by jsilhan** [comment]
use https://copr.fedoraproject.org/ probably.

**Comment by jsilhan** [comment]
* it should upload only successful builds otherwise send email to `jsilhan@redhat.com` when it fails

**Comment by jsilhan** [comment]
- [ ] register "ci-nightly" username on https://admin.fedoraproject.org/accounts/user/new
- [ ] upload srpm to github rh-lab-q/rpg srpm branch (git rm <old> && git add <new> && git commit -am "new srpm from <7_chars_of_commit_hash_from_upstream>"
- [ ] use rpg.copr_uploader API with url to srpm uploaded to github
- [ ] hide fedorahosted token in travis

**Comment by PavolVican** [comment]
I have problem with copr. Package copr-cli is not available on Ubuntu.

**Comment by jsilhan** [comment]
I am sorry, I forgot to answer. Do it the same way as tito installation from tarball.
AFAIK copr-cli has just one dependency python-copr.
- [ ] find the upstream repo of copr-cli and python-copr
- [ ] read the instructions (README) how to install it from tarball
- [ ] setup the installation in travis build script
(it seems like we could have used just `python-copr` instead of `copr-cli`, @regeciovad , but we hadn't know that) [1]

[1] http://python-copr.readthedocs.org/en/latest/Examples.html
