### ISSUE TITLE
Build uses old-generated spec file

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#161]
This won't work like we want because old spec file may still exists and will not be overwritten:
```python
if not self.spec_path.exists():
    self.write_spec()
```

**Comment by cibo94** [comment]
Possible solution
=============
```python
if not self.spec_path.exists():
    self.write_spec()
```
should be replace with this:
```python
self.write_spec()
```

If we rewrite spec file, this will be fixed, but test ```BuildSrpmTest``` will fail, because it uses external spec file, that will be overwritten. This also can be fixed by adding properties manually. Or we can simply add flag which says that spec file is external.

**Comment by jsilhan** [comment]
Was it fixed in any of your recent commits? If not do it as you suggest.

**Comment by jsilhan** [comment]
> If we rewrite spec file, this will be fixed, but test BuildSrpmTest will fail, because it uses external spec file, that will be overwritten. This also can be fixed by adding properties manually. Or we can simply add flag which says that spec file is external.

We can call just `base._package_builder.build_srpm`
