### ISSUE TITLE
Python plugin did find python3-qt5 but mock didn't install it

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#179]
https://github.com/cibo94/rpg/commit/1b8e8da8d225a822177a9d62d91be10d7c6983d3
This commit makes tests for existence of programs/libraries universal for all unix-based systems.
CMake still has not found Python3QT5 even though it was in required files:
```
python3-pygpgme
rpm-python3
python3-six
python3-iniparse
glibc-headers
python3-dnf
>>> python3-qt5 <<<
python3-librepo
python3-libs
python3-hawkey
filesystem
python3-libcomps
```

**Comment by cibo94** [comment]
CMake report:
```
-- Found PythonInterp: /usr/bin/python3.4 (found suitable version "3.4.2", minimum required is "3.4") 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'PyQt5'
CMake Error at CMakeLists.txt:19 (MESSAGE):
  Python3QT5 is missing!
```

**Comment by cibo94** [comment]
Maybe it is because Python plugin did find only python3-qt5 and not python3-qt5-devel

**Comment by jsilhan** [comment]
@cibo94 Can you please list the required files found from python plugin, error messages from converting files -> packages using dnf.query and result of `sack.query().filter(name="python3-qt5")[0].files`?

**Comment by jsilhan** [comment]
@cibo94 is it still actual?

**Comment by cibo94** [comment]
I think this is for now fixed
