### ISSUE TITLE
setup Coverage tests

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#213]
- [ ] setup nosetests
- [ ] setup travis CI

**Comment by cibo94** [comment]
I have found much better api instead of coveralls, it is called codecov and it is working significantly better! see for yourself on https://codecov.io/#features.

**Comment by jsilhan** [comment]
so is it working or #223 blocks it?

**Comment by cibo94** [comment]
yes

**Comment by jsilhan** [comment]
@cibo94 for which part was that **yes** targeted?

**Comment by cibo94** [comment]
Sorry. Yes #223 blocks it, but that issue may be caused by #221 in which spec class preserves all tag (because they are class variables) when new instance is created, because the error only appears, when tests are run massively at once via nosetests.
