### ISSUE TITLE
Spec attrs refactoring

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#219]
to have it visible in docs and make it properly working, we need to:
- [ ] make all "hidden dict" attributes normal class attributes (they should be named and accessible the same (except we couldn't use spec["bla"] anymore)
- [ ] make Provides, Requires and BuildRequires, build_required_files and required_files a sets
- [ ] make sure all tests pass and fix the ones in test_spec.py

**Comment by LukasSlouka** [comment]
I assume by "hidden dict" attributes you mean those called `tags`. If I make them class attributes, is there even a point of keeping it subclass of `dict`? I would not be able to access them through dict methods anyway. It will require additional changes in `_get methods`. 

Also I do not know what you mean by `make Provides, Requires and BuildRequires, build_required_files and required_files a sets`. Is it just renaming?

**Comment by cibo94** [comment]
I think he meant to change type of Provides and so on from [list](https://docs.python.org/2/tutorial/datastructures.html#more-on-lists) to [set](https://docs.python.org/2/library/sets.html)

**Comment by LukasSlouka** [comment]
Ok I will do that then

**Comment by LukasSlouka** [comment]
I changed them to sets but it created additional failed tests in `test_plugin.py` and `test_functional.py`. I will try to trace the problems there. In the meantime please look at the commit https://github.com/LukasSlouka/rpg/commit/2bb76c4aa8ded7a1fa1a57dc82daeee3fc8ce747 to see if I am doing it right please. The tests are all passing

**Comment by LukasSlouka** [comment]
It required changes in multiple files but it seems to be working as it should. All tests are passing now, however it is possible that I missed some changes regarding type conversion to `set` in some plugin (it depends on how good the tests actually are). I double checked it but there is slight possibility that it may cause bugs in the future.
