### ISSUE TITLE
Base and Spec docs not shown

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#231]
This [1] is built from the upstream but suddenly doesn't show any attributes or methods for `Spec` and `Base`. Do you know whats going wrong, @LukasSlouka ? Is the doc generated fine in local build?

[1] http://rpg.readthedocs.org/en/latest/

**Comment by LukasSlouka** [comment]
Hmm it did make good documentation both before and after rebase

**Comment by LukasSlouka** [comment]
Do we need it to work on `readthedocs`?? I am not sure that the problem is caused by us. I have done some googling and it seems as there are/were some issues with python 3 and readthedocs

**Comment by LukasSlouka** [comment]
Okay I managed to solve it. Check [1]. However I had to mock modules I suspect are not supposed to be mocked (all the `rpg` ones, because they are not doing problems locally).
