### ISSUE TITLE
Mock is not building rpms to resultdir

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#251]
There is a problem with following command (or mock):
```
mock --no-clean --no-cleanup-after --verbose --root x86-64 --rebuild mock.src.rpm --resultdir=/tmp
```
in man pages ```--resultdir``` should be directory where rpm and logs are stored, but there is not rpm built.

**Comment by cibo94** [comment]
Yeah I know now why. It was problem with test package that called program ```bam```, which fails, not because it doesn't exists but there was runtime error so rpm doesn't built.

**Comment by cibo94** [comment]
I have another problem ... this command I mentioned runs well now but in result directory I found only .src.rpm which is really weird. Shouldn't that command build rpm from src.rpm?

**Comment by jsilhan** [comment]
Miro, did you tried `locate <pkgname>*.rpm`? I believe it will be somewhere. If you really don't find it, [fill the bug for mock component](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=mock) and describe the bug, please.

**Comment by cibo94** [comment]
I know where problem is...

```
Getting requirements for rpg-0.0.2-1.fc22.src

 --> cmake-3.2.2-1.fc22.x86_64

 --> Already installed : filesystem-3.2-32.fc22.x86_64

 --> Already installed : glibc-headers-2.21-7.fc22.x86_64

 --> python3-copr-1.57-1.fc22.noarch

 --> python3-dnf-1.1.0-2.fc22.noarch

 --> python3-hawkey-0.6.0-1.fc22.x86_64

 --> python3-iniparse-0.4-15.fc22.noarch

 --> python3-libcomps-0.1.6-14.fc22.x86_64

 --> python3-librepo-1.7.16-1.fc22.x86_64

 --> python3-pygpgme-0.3-12.fc22.x86_64

 --> Already installed : python3-qt5-5.4.1-5.fc22.x86_64

 --> python3-requests-2.7.0-1.fc22.noarch

 --> python3-six-1.9.0-1.fc22.noarch

 --> rpm-python3-4.12.0.1-12.fc22.x86_64

Error: No Package found for python34-libs
```

But that package has been found by dnf:
```
± % sudo dnf search python34-libs
Last metadata expiration check performed 2:18:34 ago on Mon Aug 17 21:55:58 2015.
=========================================================== N/S Matched: python34-libs ============================================================
python34-libs.x86_64 : Python 3 runtime libraries
```

**Comment by cibo94** [comment]
There was problem with non-standart repo which I added
