### ISSUE TITLE
python plugin (add .pyo and .pyc files into `%files)

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#253]
see: https://github.com/rh-lab-q/rpg/pull/252#issuecomment-131529818

**Comment by LukasSlouka** [comment]
This may be kinda tricky. Read [this](http://www.network-theory.co.uk/docs/pytut/CompiledPythonfiles.html). If we count on the fact that those files will be there, it may just cause additional errors. Besides there are cases when these files are in `__pycache__` folder and that is just another issue.

**Comment by LukasSlouka** [comment]
This issue should fix __pycache__ directories as well in my opinion.

**Comment by jsilhan** [comment]
https://docs.python.org/2/library/py_compile.html
