### ISSUE TITLE
run `run_extracted_source_analysis` after Import Page + prefill fields with spec attributes in Mandatory Page

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#280]
as was suggested in https://github.com/rh-lab-q/rpg/issues/130#issuecomment-137812404

**Comment by regeciovad** [comment]
I wrote it already in comment. Spec attributes are set in Mandatory page, but not with run_extracted_source_analysis. According to me, in current project is no way to suggest attributes before user writes them. If plugins can read these before from the package and set spec attributes, it does not do it now.
