### ISSUE TITLE
python plugin should not exclude dirs where are no python files

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#282]
see this: https://github.com/rh-lab-q/rpg/pull/279/files#diff-fe57f3907c0a5391648fec641ebc389bL111

**Comment by jsilhan** [comment]
related to #281

**Comment by ignatenkobrain** [comment]
yes. we shouldn't exclude `__pycache__` at all in python specs.

**Comment by jsilhan** [comment]
yeah, we should rather generate the bytecode and include it in rpm package

**Comment by jsilhan** [comment]
duplicate of #253
