### ISSUE TITLE
Copr page: make one distro dropdown menu and check boxes only for arches

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#292]
all architectures should be checked by default and neweest version of Fedora be selected

**Comment by regeciovad** [comment]
But this way user can build package just for one distro at a time.
I can split check boxes to two section - distro and architecture, but dropdown menu is not a good option according to me.

**Comment by jsilhan** [comment]
ok, keep it as a check boxes. One column for distros, the other for architectures
