### ISSUE TITLE
Extend C plugin functionality

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#303]
See how [bash_command.py](https://github.com/rh-lab-q/rpg/blob/master/rpg%2Fplugins%2Frecover%2Fbash_command.py) is implemented.

Should catch all missing files when build fails and append them to required and build_required files.

**Comment by cibo94** [comment]
Example of gcc building error:
```
[ 94%] Building C object bindings/perl/CMakeFiles/bindings_perl.dir/solv_perl.o
/builddir/build/BUILD/LibSolv-0.6.11/bindings/perl/solv_perl.c:732:20: fatal error: EXTERN.h: No such file or directory
compilation terminated.
bindings/perl/CMakeFiles/bindings_perl.dir/build.make:60: recipe for target 'bindings/perl/CMakeFiles/bindings_perl.dir/solv_perl.o' failed
```

**Comment by jsilhan** [comment]
good idea. So parse it like this: "fatal error: $1.h: No such file or directory" -> `spec.build_requires_files.append("/usr/lib*/*$1.h")` or so

**Comment by cibo94** [comment]
I just realized that all missing files should catch already C plugin itself before even build starts. But it does not. I have to find out if algorithm failed or converting to packages

**Comment by jsilhan** [comment]
do you have the files locally? `dnf builddep libsolv`

**Comment by cibo94** [comment]
yes but mock failed because perl-devel was not in any requires in spec file - in other words  RPG  didn't find EXTERN.h (perl-devel)

**Comment by cibo94** [comment]
Neither of C programs (makedepend, gcc/g++) retrieved EXTERN.h - perl-devel dependency. So this may be, after all, useful.
