### ISSUE TITLE
COPR page: make URL of source be able to upload local SRPMs

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#309]
http://blog.samalik.com/copr-dist-git-and-patternfly/

**Comment by regeciovad** [comment]
I am a little bit confused.
Am I right, if I think this is about creating server, where users can load their srpm packages? But where it will run? Without server I can not create url, right? And am I supposed to create new user account with permission every time or it will run just with one account and one packager group?
I also tried create package via Copr Api, but there is still a need to fill url without a chance to load source to the Dist Git Server.

**Comment by jsilhan** [comment]
see https://github.com/rpm-software-management/ci-dnf-stack/blob/master/cidnfstack.py#L439 . AFAIK we upload sprm directly to COPR
