### ISSUE TITLE
Autotools plugin should append %configure to %build

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#312]
Not a ./configure

**Comment by LukasSlouka** [comment]
it does already, doesn't it?

**Comment by cibo94** [comment]
you have there ./configure there but %configure is better because of possible switches.

**Comment by cibo94** [comment]
Same in CMake plugin:
No ```cmake .``` but ```%cmake .```

**Comment by LukasSlouka** [comment]
ah did not know about this one, thanks for pointing it out
