### ISSUE TITLE
add mock tests for building libhif

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#327]
do the analogue test for libhif (https://github.com/rpm-software-management/libhif/archive/libhif_0_2_1.zip) like https://github.com/rh-lab-q/rpg/blob/master/tests/mock_build/test_build_hawkey.py

**Comment by jsilhan** [comment]
there you can see the spec of libhif: https://kojipkgs.fedoraproject.org//packages/libhif/0.2.1/4.fc23/src/libhif-0.2.1-4.fc23.src.rpm

**Comment by cibo94** [comment]
depends on #334
