### ISSUE TITLE
core dumped after clicking on "build" button

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#368]
```
[16:52:18] {/home/jsilhan/Documents/rpg/rpg/plugin_engine.py:74} INFO - executing CPlugin.mock_recover()
Traceback (most recent call last):
  File "/home/jsilhan/Documents/rpg/rpg/__init__.py", line 257, in build_rpm_recover
    build()
  File "/home/jsilhan/Documents/rpg/rpg/__init__.py", line 247, in build
    self.build_rpm(distro, arch)
  File "/home/jsilhan/Documents/rpg/rpg/__init__.py", line 239, in build_rpm
    str(self.srpm_path), target_distro, target_arch, self.base_dir)
  File "/home/jsilhan/Documents/rpg/rpg/package_builder.py", line 106, in build_rpm
    raise BuildException(_ret, self.build_ret_code)
rpg.package_builder.BuildException: DEBUG: Error: No Package found for python3-bugzilla-develdashboardfixes

ERROR: Exception(/tmp/rpg-dnf-3270cab.tar.xz-34d480e/dnf-3-1.src.rpm) Config(fedora-22-x86_64) 0 minutes 7 seconds

DEBUG: ERROR: can't perform the search - Inappropriate ioctl for device

DEBUG: ERROR: can't get rootid for '/var/lib/mock'

ERROR: Command failed: 

Error: No Package found for python3-bugzilla-develdashboardfixes


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jsilhan/Documents/rpg/rpg/gui/wizard.py", line 1038, in buildRpm
    self.base.build_rpm_recover(distro, arch)
  File "/home/jsilhan/Documents/rpg/rpg/__init__.py", line 263, in build_rpm_recover
    .format(self._package_builder.mock_logs))
RuntimeError: Build failed! See logs in '/tmp/rpg-dnf-3270cab.tar.xz-34d480e/mock_logs'
Aborted (core dumped)
```
[build.log.txt](https://github.com/rh-lab-q/rpg/files/115934/build.log.txt)
[root.log.txt](https://github.com/rh-lab-q/rpg/files/115935/root.log.txt)
[state.log.txt](https://github.com/rh-lab-q/rpg/files/115936/state.log.txt)

**Comment by LukasSlouka** [comment]
I had similar problem lately with maven dependencies. There simply were no packages for them as the error message suggest. I solved it by removing these dependencies from BuildRequires in `mock_recover` plugin phase. I suppose there could be separate plugin for that as it may cause problems anywhere.

I know that removing dependencies without the users acknowledgment is not the best solution, so maybe we could run `dnf repoquery` on all dependencies when user reaches Requires page in GUI and highlight problematic dependencies for the user and add a warning that those deps will not be available.

**Comment by jsilhan** [comment]
thanks for your insight, Lukas. I think we talked about it and the root issue is that repositories are not the same. Some packages are taken from local configuration of DNF, the other ones from from DNF conf in mock. Also the metadata are downloaded twice with current approach. This shoudl be a duplicate of #372
