### ISSUE TITLE
try build libsolv package with RPG

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#62]
follow the process of RPG (all the phases: see /tmp/rpg-*) and watch warnings -> add issues/fix it
the testing project is libsolv project folder

**Comment by jsilhan** [comment]
write long test for mock build of libsolv package. Make them pass.
use base.load_project_from_url("https://github.com/openSUSE/libsolv/archive/0.6.11.tar.gz")
depends on #175

**Comment by cibo94** [comment]
I had problems with the version you have provided so I just use self.base.load_project_from_url("https://github.com/openSUSE/libsolv/") and it works just fine 'till I hit the ```make install DESTDIR=/builddir/build/BUILDROOT/LibSolv-0.6.11-1.fc22.x86_64``` zone in mock build where I get this error:
```
[ 94%] Building C object bindings/perl/CMakeFiles/bindings_perl.dir/solv_perl.o
/builddir/build/BUILD/LibSolv-0.6.11/bindings/perl/solv_perl.c:732:20: fatal error: EXTERN.h: No such file or directory
compilation terminated.
bindings/perl/CMakeFiles/bindings_perl.dir/build.make:60: recipe for target 'bindings/perl/CMakeFiles/bindings_perl.dir/solv_perl.o' failed
CMakeFiles/Makefile2:784: recipe for target 'bindings/perl/CMakeFiles/bindings_perl.dir/all' failed
```

I think that it will be nice to catch build errors in C plugin and add missing files to required files then rebuild again.

**Comment by cibo94** [comment]
BTW ```EXTERN.h``` is header that provides embedding perl.
