### ISSUE TITLE
 try build hawkey package with RPG 

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#76]
follow the process of RPG (all the phases: see /tmp/rpg-*) and watch warnings -> add issues/fix it
the testing project is libsolv project folder. (Install libsolv rpm to fullfill dependencies)

**Comment by jsilhan** [comment]
@cibo94 was the hawkey mock build ok?

**Comment by jsilhan** [comment]
write long test for mock build of hawkey package. Make them pass (append `make doc-man` to spec.build, `expat-devel` to spec.(Build)Requires, etc.)
depends on #175

**Comment by jsilhan** [comment]
The purpose is to make mock test for this. The same structure like #225 (https://github.com/rh-lab-q/rpg/commit/84706114373fc21248bd7cd67b423e6f818d0de3) but [different sources](https://github.com/rpm-software-management/hawkey). Append to spec only the requires/buildRequires/file_requires... that wasn't completed automatically by RPG. Tip: to build hawkey properly you have to `spec.build.append("make doc-man")

**Comment by LukasSlouka** [comment]
Just out of curiosity, wouldn't we want to be able to run `make test-mock` since it is not under unit nor long tests? Or at least put all mock_build tests under long?

**Comment by LukasSlouka** [comment]
When I try to use `base.load_project_from_url("https://github.com/rpm-software-management/hawkey/archive/hawkey-0.5.7-1.tar.gz")`

I get this error:
`nose.proxy.RuntimeError: Can't download 'https:/github.com/rpm-software-management/hawkey/archive/hawkey-0.5.7-1.tar.gz' - 10 times retreated`

**Comment by LukasSlouka** [comment]
Solved by bf367542c7b483c47d2cc4bdc0ed5a0b0563a0ba

**Comment by jsilhan** [comment]
> Just out of curiosity, wouldn't we want to be able to run make test-mock since it is not under unit nor long tests? Or at least put all mock_build tests under long?

We cannot run mock tests in Travis CI. That's why we created extra category
