### ISSUE TITLE
Requires Page: print spec attributes as string when items are separated by "\n"

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#95]

**Comment by regeciovad** [comment]
Sorry, I didn't make a note about this. So, I just have to cut off "\n", or replace them with commas?

**Comment by jsilhan** [comment]
`self.bRequiresEdit.setText(str(self.base.spec.BuildRequires))` -> `self.buildRequiresEdit.setText('\n'.join(self.base.spec.BuildRequires))` for requires, buildrequires ad provides. Don't forget about parsing it from textfield back.

**Comment by regeciovad** [comment]
Thank you very much.
